# trigger rebuild
name: Build LX Images
on:
    push:
        paths-ignore:
            - '**.md'
        branches:
            - master
jobs:
    prepare:
        name: Create Release
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            tag: ${{ steps.build_tag.outputs.tag }}
        steps:
            - name: Create Time Stamp Tag
              id: build_tag
              run: date +'::set-output name=tag::%Y-%m-%d_%H-%M-%S'

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.build_tag.outputs.tag }}
                  release_name: Release ${{ steps.build_tag.outputs.tag }}
                  draft: false
                  prerelease: false

    ubuntu:
        needs: prepare
        strategy:
            matrix:
                RELEASE:
                    - 20.04
                    - 18.04

        name: Build Ubuntu ${{ matrix.RELEASE }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Image
              id: build_image
              run: |
                  set -xe
                  cd ubuntu
                  tar=lx-ubuntu-${{ matrix.RELEASE }}.tar
                  tag=release:$$
                  docker build --tag $tag --build-arg UBUNTU_RELEASE=${{ matrix.RELEASE }} .
                  container=$(docker create $tag)
                  docker cp $container:. - > $tar
                  docker rm $container
                  docker rmi $tag
                  xz $tar
            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }}
                  asset_path: ./ubuntu/lx-ubuntu-${{ matrix.RELEASE }}.tar.xz
                  asset_name: lx-ubuntu-${{ matrix.RELEASE }}-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-xz

    debian:
        needs: prepare
        strategy:
            matrix:
                RELEASE:
                    - bullseye
                    - buster

        name: Build Debian ${{ matrix.RELEASE }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Image
              id: build_image
              run: |
                  set -xe
                  cd debian
                  tar=lx-debian-${{ matrix.RELEASE }}.tar
                  tag=release:$$
                  docker build --tag $tag --build-arg DEBIAN_RELEASE=${{ matrix.RELEASE }} .
                  container=$(docker create $tag)
                  docker cp $container:. - > $tar
                  docker rm $container
                  docker rmi $tag
                  xz $tar
            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }}
                  asset_path: ./debian/lx-debian-${{ matrix.RELEASE }}.tar.xz
                  asset_name: lx-debian-${{ matrix.RELEASE }}-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-xz

    devuan:
        needs: prepare
        strategy:
            matrix:
                RELEASE:
                    - beowulf

        name: Build Devuan ${{ matrix.RELEASE }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Image
              id: build_image
              run: |
                  set -xe
                  cd devuan
                  tar=lx-devuan-${{ matrix.RELEASE }}.tar
                  tag=release:$$
                  docker build --tag $tag --build-arg DEVUAN_RELEASE=${{ matrix.RELEASE }} .
                  container=$(docker create $tag)
                  docker cp $container:. - > $tar
                  docker rm $container
                  docker rmi $tag
                  xz $tar
            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }}
                  asset_path: ./devuan/lx-devuan-${{ matrix.RELEASE }}.tar.xz
                  asset_name: lx-devuan-${{ matrix.RELEASE }}-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-xz

    void:
        needs: prepare

        name: Build void image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Image
              id: build_image
              run: |
                  cd void
                  tar=lx-void.tar
                  tag=release:$$
                  docker build --tag $tag .
                  container=$(docker create $tag)
                  docker cp $container:. - > $tar
                  docker rm $container
                  docker rmi $tag
                  xz $tar
            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }}
                  asset_path: ./void/lx-void.tar.xz
                  asset_name: lx-void-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-xz

    centos:
        needs: prepare
        strategy:
            matrix:
                RELEASE:
                    - 8

        name: Build Centos ${{ matrix.RELEASE }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Image
              id: build_image
              run: |
                  set -xe
                  cd centos
                  tar=lx-centos-${{ matrix.RELEASE }}.tar
                  tag=release:$$
                  docker build --tag $tag --build-arg CENTOS_RELEASE=${{ matrix.RELEASE }} .
                  container=$(docker create $tag)
                  docker cp $container:. - > $tar
                  docker rm $container
                  docker rmi $tag
                  xz $tar
            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }}
                  asset_path: ./centos/lx-centos-${{ matrix.RELEASE }}.tar.xz
                  asset_name: lx-centos-${{ matrix.RELEASE }}-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-xz
